const ACTION_TYPES = {
  GET_USERS_LIST: 'GET_USERS_LIST',
  GET_EDIT_USER: 'GET_EDIT_USER',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILED: 'EDIT_USER_FAILED',
  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST'
};

export { ACTION_TYPES };
